# GitHub Personal Access Token
github_token = ""

# IPA Service Configuration
ipa_base_url = "https://ipa.aspy.dev/discord"
github_repo = "castdrian/PyoncordTweak"

# Service Configuration
refresh_interval = 3600 