# IPA Service Configuration
ipa_base_url = "https://ipa.aspy.dev/discord"

# Service Configuration
refresh_interval = 900 # 15 minutes

# Target Repo Configuration
[[targets]]
github_repo = "castdrian/PyoncordTweak"
github_token = ""

[[targets]]
github_repo = "unbound-app/loader-ios"
github_token = ""
