# ipa service configuration
ipa_base_url = "https://ipa.aspy.dev/discord"

# service configuration
refresh_interval = 900 # 15 minutes

# target repo configuration
[[targets]]
github_repo = "user/repo"
github_token = "github_pat_..."

[[targets]]
github_repo = "org/repo"
github_token = "github_pat_..."
