# ipa service configuration
ipa_base_url = "https://ipa.aspy.dev/discord"

# service configuration
refresh_schedule = "0,15,30,45 * * * *" # every quarter hour (00,15,30,45)

# target repo configuration
[[targets]]
github_repo = "user/repo"
github_token = "github_pat_..."

[[targets]]
github_repo = "org/repo"
github_token = "github_pat_..."